### ISSUE TITLE
linux csv文件无法读取

### ISSUE THREAD

**Issue by wssysh** [iShareStuff/ZoteroIF-Plugin-for-Zotero#3]
up，你好，linux无法使用此插件。应该是路径问题，无法读取csv文件

**Comment by iShareStuff** [comment]
你咋设置的路径

**Comment by wssysh** [comment]
up你好，我设置的是绝对路径 /home/username/Downloads/default.csv ，zotero最新版，os : manjaro linux。由于正在上课，具体信息我晚些时间再回复你。

**Comment by iShareStuff** [comment]
我的没有问题，deepin系统【Ubuntu】。路径没有问题，是绝对路径。

**Comment by iShareStuff** [comment]
/home/share/Desktop/a.csv

![image](https://user-images.githubusercontent.com/61663626/164228457-d49344d3-48f5-4580-b507-c7a853b1ac6c.png)

**Comment by wssysh** [comment]
你好，确定之后是我的路径存在问题，打扰up了。感谢up的及时回复！

**Comment by iShareStuff** [comment]
这不推广一下，哈哈哈。加油

**Comment by wssysh** [comment]
那是肯定的，再次感谢up
